// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string RFW_ID = 1;</code>
     * @return Whether the rFWID field is set.
     */
    boolean hasRFWID();
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The rFWID.
     */
    String getRFWID();
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The bytes for rFWID.
     */
    com.google.protobuf.ByteString
        getRFWIDBytes();

    /**
     * <code>required string Benchmark = 2;</code>
     * @return Whether the benchmark field is set.
     */
    boolean hasBenchmark();
    /**
     * <code>required string Benchmark = 2;</code>
     * @return The benchmark.
     */
    String getBenchmark();
    /**
     * <code>required string Benchmark = 2;</code>
     * @return The bytes for benchmark.
     */
    com.google.protobuf.ByteString
        getBenchmarkBytes();

    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return Whether the workloadMetric field is set.
     */
    boolean hasWorkloadMetric();
    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return The workloadMetric.
     */
    String getWorkloadMetric();
    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return The bytes for workloadMetric.
     */
    com.google.protobuf.ByteString
        getWorkloadMetricBytes();

    /**
     * <code>required int32 Batch_Unit = 4;</code>
     * @return Whether the batchUnit field is set.
     */
    boolean hasBatchUnit();
    /**
     * <code>required int32 Batch_Unit = 4;</code>
     * @return The batchUnit.
     */
    int getBatchUnit();

    /**
     * <code>required int32 Batch_ID = 5;</code>
     * @return Whether the batchID field is set.
     */
    boolean hasBatchID();
    /**
     * <code>required int32 Batch_ID = 5;</code>
     * @return The batchID.
     */
    int getBatchID();

    /**
     * <code>required int32 Batch_Size = 6;</code>
     * @return Whether the batchSize field is set.
     */
    boolean hasBatchSize();
    /**
     * <code>required int32 Batch_Size = 6;</code>
     * @return The batchSize.
     */
    int getBatchSize();

    /**
     * <code>required string Data_Type = 7;</code>
     * @return Whether the dataType field is set.
     */
    boolean hasDataType();
    /**
     * <code>required string Data_Type = 7;</code>
     * @return The dataType.
     */
    String getDataType();
    /**
     * <code>required string Data_Type = 7;</code>
     * @return The bytes for dataType.
     */
    com.google.protobuf.ByteString
        getDataTypeBytes();
  }
  /**
   * Protobuf type {@code RequestProto}
   */
  public static final class RequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestProto)
      RequestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestProto.newBuilder() to construct.
    private RequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProto() {
      rFWID_ = "";
      benchmark_ = "";
      workloadMetric_ = "";
      dataType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestProto();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              rFWID_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              benchmark_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              workloadMetric_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              batchUnit_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              batchID_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              batchSize_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              dataType_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Request.internal_static_RequestProto_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Request.internal_static_RequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestProto.class, Builder.class);
    }

    private int bitField0_;
    public static final int RFW_ID_FIELD_NUMBER = 1;
    private volatile Object rFWID_;
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return Whether the rFWID field is set.
     */
    @Override
    public boolean hasRFWID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The rFWID.
     */
    @Override
    public String getRFWID() {
      Object ref = rFWID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rFWID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The bytes for rFWID.
     */
    @Override
    public com.google.protobuf.ByteString
        getRFWIDBytes() {
      Object ref = rFWID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rFWID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BENCHMARK_FIELD_NUMBER = 2;
    private volatile Object benchmark_;
    /**
     * <code>required string Benchmark = 2;</code>
     * @return Whether the benchmark field is set.
     */
    @Override
    public boolean hasBenchmark() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string Benchmark = 2;</code>
     * @return The benchmark.
     */
    @Override
    public String getBenchmark() {
      Object ref = benchmark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          benchmark_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Benchmark = 2;</code>
     * @return The bytes for benchmark.
     */
    @Override
    public com.google.protobuf.ByteString
        getBenchmarkBytes() {
      Object ref = benchmark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        benchmark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKLOAD_METRIC_FIELD_NUMBER = 3;
    private volatile Object workloadMetric_;
    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return Whether the workloadMetric field is set.
     */
    @Override
    public boolean hasWorkloadMetric() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return The workloadMetric.
     */
    @Override
    public String getWorkloadMetric() {
      Object ref = workloadMetric_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          workloadMetric_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Workload_Metric = 3;</code>
     * @return The bytes for workloadMetric.
     */
    @Override
    public com.google.protobuf.ByteString
        getWorkloadMetricBytes() {
      Object ref = workloadMetric_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        workloadMetric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCH_UNIT_FIELD_NUMBER = 4;
    private int batchUnit_;
    /**
     * <code>required int32 Batch_Unit = 4;</code>
     * @return Whether the batchUnit field is set.
     */
    @Override
    public boolean hasBatchUnit() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 Batch_Unit = 4;</code>
     * @return The batchUnit.
     */
    @Override
    public int getBatchUnit() {
      return batchUnit_;
    }

    public static final int BATCH_ID_FIELD_NUMBER = 5;
    private int batchID_;
    /**
     * <code>required int32 Batch_ID = 5;</code>
     * @return Whether the batchID field is set.
     */
    @Override
    public boolean hasBatchID() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 Batch_ID = 5;</code>
     * @return The batchID.
     */
    @Override
    public int getBatchID() {
      return batchID_;
    }

    public static final int BATCH_SIZE_FIELD_NUMBER = 6;
    private int batchSize_;
    /**
     * <code>required int32 Batch_Size = 6;</code>
     * @return Whether the batchSize field is set.
     */
    @Override
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 Batch_Size = 6;</code>
     * @return The batchSize.
     */
    @Override
    public int getBatchSize() {
      return batchSize_;
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 7;
    private volatile Object dataType_;
    /**
     * <code>required string Data_Type = 7;</code>
     * @return Whether the dataType field is set.
     */
    @Override
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string Data_Type = 7;</code>
     * @return The dataType.
     */
    @Override
    public String getDataType() {
      Object ref = dataType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Data_Type = 7;</code>
     * @return The bytes for dataType.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRFWID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBenchmark()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorkloadMetric()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBatchUnit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBatchID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBatchSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rFWID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, benchmark_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, workloadMetric_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, batchUnit_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, batchID_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, batchSize_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dataType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rFWID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, benchmark_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, workloadMetric_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchUnit_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchID_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, batchSize_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dataType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestProto)) {
        return super.equals(obj);
      }
      RequestProto other = (RequestProto) obj;

      if (hasRFWID() != other.hasRFWID()) return false;
      if (hasRFWID()) {
        if (!getRFWID()
            .equals(other.getRFWID())) return false;
      }
      if (hasBenchmark() != other.hasBenchmark()) return false;
      if (hasBenchmark()) {
        if (!getBenchmark()
            .equals(other.getBenchmark())) return false;
      }
      if (hasWorkloadMetric() != other.hasWorkloadMetric()) return false;
      if (hasWorkloadMetric()) {
        if (!getWorkloadMetric()
            .equals(other.getWorkloadMetric())) return false;
      }
      if (hasBatchUnit() != other.hasBatchUnit()) return false;
      if (hasBatchUnit()) {
        if (getBatchUnit()
            != other.getBatchUnit()) return false;
      }
      if (hasBatchID() != other.hasBatchID()) return false;
      if (hasBatchID()) {
        if (getBatchID()
            != other.getBatchID()) return false;
      }
      if (hasBatchSize() != other.hasBatchSize()) return false;
      if (hasBatchSize()) {
        if (getBatchSize()
            != other.getBatchSize()) return false;
      }
      if (hasDataType() != other.hasDataType()) return false;
      if (hasDataType()) {
        if (!getDataType()
            .equals(other.getDataType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRFWID()) {
        hash = (37 * hash) + RFW_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRFWID().hashCode();
      }
      if (hasBenchmark()) {
        hash = (37 * hash) + BENCHMARK_FIELD_NUMBER;
        hash = (53 * hash) + getBenchmark().hashCode();
      }
      if (hasWorkloadMetric()) {
        hash = (37 * hash) + WORKLOAD_METRIC_FIELD_NUMBER;
        hash = (53 * hash) + getWorkloadMetric().hashCode();
      }
      if (hasBatchUnit()) {
        hash = (37 * hash) + BATCH_UNIT_FIELD_NUMBER;
        hash = (53 * hash) + getBatchUnit();
      }
      if (hasBatchID()) {
        hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
        hash = (53 * hash) + getBatchID();
      }
      if (hasBatchSize()) {
        hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getBatchSize();
      }
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDataType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestProto)
        RequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Request.internal_static_RequestProto_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Request.internal_static_RequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestProto.class, Builder.class);
      }

      // Construct using com.Coen424.Assignment1.Request.RequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rFWID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        benchmark_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        workloadMetric_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        batchUnit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        batchID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        batchSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        dataType_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Request.internal_static_RequestProto_descriptor;
      }

      @Override
      public RequestProto getDefaultInstanceForType() {
        return RequestProto.getDefaultInstance();
      }

      @Override
      public RequestProto build() {
        RequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestProto buildPartial() {
        RequestProto result = new RequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rFWID_ = rFWID_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.benchmark_ = benchmark_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workloadMetric_ = workloadMetric_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batchUnit_ = batchUnit_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batchID_ = batchID_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.batchSize_ = batchSize_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dataType_ = dataType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestProto) {
          return mergeFrom((RequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestProto other) {
        if (other == RequestProto.getDefaultInstance()) return this;
        if (other.hasRFWID()) {
          bitField0_ |= 0x00000001;
          rFWID_ = other.rFWID_;
          onChanged();
        }
        if (other.hasBenchmark()) {
          bitField0_ |= 0x00000002;
          benchmark_ = other.benchmark_;
          onChanged();
        }
        if (other.hasWorkloadMetric()) {
          bitField0_ |= 0x00000004;
          workloadMetric_ = other.workloadMetric_;
          onChanged();
        }
        if (other.hasBatchUnit()) {
          setBatchUnit(other.getBatchUnit());
        }
        if (other.hasBatchID()) {
          setBatchID(other.getBatchID());
        }
        if (other.hasBatchSize()) {
          setBatchSize(other.getBatchSize());
        }
        if (other.hasDataType()) {
          bitField0_ |= 0x00000040;
          dataType_ = other.dataType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasRFWID()) {
          return false;
        }
        if (!hasBenchmark()) {
          return false;
        }
        if (!hasWorkloadMetric()) {
          return false;
        }
        if (!hasBatchUnit()) {
          return false;
        }
        if (!hasBatchID()) {
          return false;
        }
        if (!hasBatchSize()) {
          return false;
        }
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object rFWID_ = "";
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return Whether the rFWID field is set.
       */
      public boolean hasRFWID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return The rFWID.
       */
      public String getRFWID() {
        Object ref = rFWID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rFWID_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return The bytes for rFWID.
       */
      public com.google.protobuf.ByteString
          getRFWIDBytes() {
        Object ref = rFWID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rFWID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @param value The rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rFWID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rFWID_ = getDefaultInstance().getRFWID();
        onChanged();
        return this;
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @param value The bytes for rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rFWID_ = value;
        onChanged();
        return this;
      }

      private Object benchmark_ = "";
      /**
       * <code>required string Benchmark = 2;</code>
       * @return Whether the benchmark field is set.
       */
      public boolean hasBenchmark() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string Benchmark = 2;</code>
       * @return The benchmark.
       */
      public String getBenchmark() {
        Object ref = benchmark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            benchmark_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Benchmark = 2;</code>
       * @return The bytes for benchmark.
       */
      public com.google.protobuf.ByteString
          getBenchmarkBytes() {
        Object ref = benchmark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          benchmark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Benchmark = 2;</code>
       * @param value The benchmark to set.
       * @return This builder for chaining.
       */
      public Builder setBenchmark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        benchmark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Benchmark = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBenchmark() {
        bitField0_ = (bitField0_ & ~0x00000002);
        benchmark_ = getDefaultInstance().getBenchmark();
        onChanged();
        return this;
      }
      /**
       * <code>required string Benchmark = 2;</code>
       * @param value The bytes for benchmark to set.
       * @return This builder for chaining.
       */
      public Builder setBenchmarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        benchmark_ = value;
        onChanged();
        return this;
      }

      private Object workloadMetric_ = "";
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @return Whether the workloadMetric field is set.
       */
      public boolean hasWorkloadMetric() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @return The workloadMetric.
       */
      public String getWorkloadMetric() {
        Object ref = workloadMetric_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            workloadMetric_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @return The bytes for workloadMetric.
       */
      public com.google.protobuf.ByteString
          getWorkloadMetricBytes() {
        Object ref = workloadMetric_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          workloadMetric_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @param value The workloadMetric to set.
       * @return This builder for chaining.
       */
      public Builder setWorkloadMetric(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workloadMetric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkloadMetric() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workloadMetric_ = getDefaultInstance().getWorkloadMetric();
        onChanged();
        return this;
      }
      /**
       * <code>required string Workload_Metric = 3;</code>
       * @param value The bytes for workloadMetric to set.
       * @return This builder for chaining.
       */
      public Builder setWorkloadMetricBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workloadMetric_ = value;
        onChanged();
        return this;
      }

      private int batchUnit_ ;
      /**
       * <code>required int32 Batch_Unit = 4;</code>
       * @return Whether the batchUnit field is set.
       */
      @Override
      public boolean hasBatchUnit() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 Batch_Unit = 4;</code>
       * @return The batchUnit.
       */
      @Override
      public int getBatchUnit() {
        return batchUnit_;
      }
      /**
       * <code>required int32 Batch_Unit = 4;</code>
       * @param value The batchUnit to set.
       * @return This builder for chaining.
       */
      public Builder setBatchUnit(int value) {
        bitField0_ |= 0x00000008;
        batchUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Batch_Unit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchUnit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batchUnit_ = 0;
        onChanged();
        return this;
      }

      private int batchID_ ;
      /**
       * <code>required int32 Batch_ID = 5;</code>
       * @return Whether the batchID field is set.
       */
      @Override
      public boolean hasBatchID() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 Batch_ID = 5;</code>
       * @return The batchID.
       */
      @Override
      public int getBatchID() {
        return batchID_;
      }
      /**
       * <code>required int32 Batch_ID = 5;</code>
       * @param value The batchID to set.
       * @return This builder for chaining.
       */
      public Builder setBatchID(int value) {
        bitField0_ |= 0x00000010;
        batchID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Batch_ID = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batchID_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>required int32 Batch_Size = 6;</code>
       * @return Whether the batchSize field is set.
       */
      @Override
      public boolean hasBatchSize() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 Batch_Size = 6;</code>
       * @return The batchSize.
       */
      @Override
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>required int32 Batch_Size = 6;</code>
       * @param value The batchSize to set.
       * @return This builder for chaining.
       */
      public Builder setBatchSize(int value) {
        bitField0_ |= 0x00000020;
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Batch_Size = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        batchSize_ = 0;
        onChanged();
        return this;
      }

      private Object dataType_ = "";
      /**
       * <code>required string Data_Type = 7;</code>
       * @return Whether the dataType field is set.
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string Data_Type = 7;</code>
       * @return The dataType.
       */
      public String getDataType() {
        Object ref = dataType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Data_Type = 7;</code>
       * @return The bytes for dataType.
       */
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Data_Type = 7;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Data_Type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dataType_ = getDefaultInstance().getDataType();
        onChanged();
        return this;
      }
      /**
       * <code>required string Data_Type = 7;</code>
       * @param value The bytes for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dataType_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestProto)
    }

    // @@protoc_insertion_point(class_scope:RequestProto)
    private static final RequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestProto();
    }

    public static RequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<RequestProto>
        PARSER = new com.google.protobuf.AbstractParser<RequestProto>() {
      @Override
      public RequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestProto> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rRequest.proto\"\227\001\n\014RequestProto\022\016\n\006RFW_" +
      "ID\030\001 \002(\t\022\021\n\tBenchmark\030\002 \002(\t\022\027\n\017Workload_" +
      "Metric\030\003 \002(\t\022\022\n\nBatch_Unit\030\004 \002(\005\022\020\n\010Batc" +
      "h_ID\030\005 \002(\005\022\022\n\nBatch_Size\030\006 \002(\005\022\021\n\tData_T" +
      "ype\030\007 \002(\tB\031\n\027com.Coen424.Assignment1"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProto_descriptor,
        new String[] { "RFWID", "Benchmark", "WorkloadMetric", "BatchUnit", "BatchID", "BatchSize", "DataType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
