// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string RFW_ID = 1;</code>
     * @return Whether the rFWID field is set.
     */
    boolean hasRFWID();
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The rFWID.
     */
    String getRFWID();
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The bytes for rFWID.
     */
    com.google.protobuf.ByteString
        getRFWIDBytes();

    /**
     * <code>required int32 last_batch_ID = 2;</code>
     * @return Whether the lastBatchID field is set.
     */
    boolean hasLastBatchID();
    /**
     * <code>required int32 last_batch_ID = 2;</code>
     * @return The lastBatchID.
     */
    int getLastBatchID();

    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    java.util.List<ResponseProto.Record>
        getBatchList();
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    ResponseProto.Record getBatch(int index);
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    int getBatchCount();
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    java.util.List<? extends ResponseProto.RecordOrBuilder>
        getBatchOrBuilderList();
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    ResponseProto.RecordOrBuilder getBatchOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResponseProto}
   */
  public static final class ResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseProto)
      ResponseProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseProto.newBuilder() to construct.
    private ResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProto() {
      rFWID_ = "";
      batch_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseProto();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              rFWID_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lastBatchID_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                batch_ = new java.util.ArrayList<Record>();
                mutable_bitField0_ |= 0x00000004;
              }
              batch_.add(
                  input.readMessage(Record.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          batch_ = java.util.Collections.unmodifiableList(batch_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_ResponseProto_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_ResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseProto.class, Builder.class);
    }

    public interface RecordOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ResponseProto.Record)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required double CPU = 1;</code>
       * @return Whether the cPU field is set.
       */
      boolean hasCPU();
      /**
       * <code>required double CPU = 1;</code>
       * @return The cPU.
       */
      double getCPU();

      /**
       * <code>required double net_in = 2;</code>
       * @return Whether the netIn field is set.
       */
      boolean hasNetIn();
      /**
       * <code>required double net_in = 2;</code>
       * @return The netIn.
       */
      double getNetIn();

      /**
       * <code>required double net_out = 3;</code>
       * @return Whether the netOut field is set.
       */
      boolean hasNetOut();
      /**
       * <code>required double net_out = 3;</code>
       * @return The netOut.
       */
      double getNetOut();

      /**
       * <code>required double memory = 4;</code>
       * @return Whether the memory field is set.
       */
      boolean hasMemory();
      /**
       * <code>required double memory = 4;</code>
       * @return The memory.
       */
      double getMemory();

      /**
       * <code>required bool training_or_testing = 5;</code>
       * @return Whether the trainingOrTesting field is set.
       */
      boolean hasTrainingOrTesting();
      /**
       * <code>required bool training_or_testing = 5;</code>
       * @return The trainingOrTesting.
       */
      boolean getTrainingOrTesting();

      /**
       * <code>required bool DVD_or_NDBench = 6;</code>
       * @return Whether the dVDOrNDBench field is set.
       */
      boolean hasDVDOrNDBench();
      /**
       * <code>required bool DVD_or_NDBench = 6;</code>
       * @return The dVDOrNDBench.
       */
      boolean getDVDOrNDBench();
    }
    /**
     * Protobuf type {@code ResponseProto.Record}
     */
    public static final class Record extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ResponseProto.Record)
        RecordOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Record.newBuilder() to construct.
      private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Record() {
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new Record();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Record(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                bitField0_ |= 0x00000001;
                cPU_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                netIn_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                netOut_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                memory_ = input.readDouble();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                trainingOrTesting_ = input.readBool();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                dVDOrNDBench_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_ResponseProto_Record_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_ResponseProto_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Record.class, Builder.class);
      }

      private int bitField0_;
      public static final int CPU_FIELD_NUMBER = 1;
      private double cPU_;
      /**
       * <code>required double CPU = 1;</code>
       * @return Whether the cPU field is set.
       */
      @Override
      public boolean hasCPU() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double CPU = 1;</code>
       * @return The cPU.
       */
      @Override
      public double getCPU() {
        return cPU_;
      }

      public static final int NET_IN_FIELD_NUMBER = 2;
      private double netIn_;
      /**
       * <code>required double net_in = 2;</code>
       * @return Whether the netIn field is set.
       */
      @Override
      public boolean hasNetIn() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double net_in = 2;</code>
       * @return The netIn.
       */
      @Override
      public double getNetIn() {
        return netIn_;
      }

      public static final int NET_OUT_FIELD_NUMBER = 3;
      private double netOut_;
      /**
       * <code>required double net_out = 3;</code>
       * @return Whether the netOut field is set.
       */
      @Override
      public boolean hasNetOut() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double net_out = 3;</code>
       * @return The netOut.
       */
      @Override
      public double getNetOut() {
        return netOut_;
      }

      public static final int MEMORY_FIELD_NUMBER = 4;
      private double memory_;
      /**
       * <code>required double memory = 4;</code>
       * @return Whether the memory field is set.
       */
      @Override
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double memory = 4;</code>
       * @return The memory.
       */
      @Override
      public double getMemory() {
        return memory_;
      }

      public static final int TRAINING_OR_TESTING_FIELD_NUMBER = 5;
      private boolean trainingOrTesting_;
      /**
       * <code>required bool training_or_testing = 5;</code>
       * @return Whether the trainingOrTesting field is set.
       */
      @Override
      public boolean hasTrainingOrTesting() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bool training_or_testing = 5;</code>
       * @return The trainingOrTesting.
       */
      @Override
      public boolean getTrainingOrTesting() {
        return trainingOrTesting_;
      }

      public static final int DVD_OR_NDBENCH_FIELD_NUMBER = 6;
      private boolean dVDOrNDBench_;
      /**
       * <code>required bool DVD_or_NDBench = 6;</code>
       * @return Whether the dVDOrNDBench field is set.
       */
      @Override
      public boolean hasDVDOrNDBench() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required bool DVD_or_NDBench = 6;</code>
       * @return The dVDOrNDBench.
       */
      @Override
      public boolean getDVDOrNDBench() {
        return dVDOrNDBench_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCPU()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNetIn()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNetOut()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMemory()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTrainingOrTesting()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDVDOrNDBench()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeDouble(1, cPU_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(2, netIn_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeDouble(3, netOut_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeDouble(4, memory_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          output.writeBool(5, trainingOrTesting_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          output.writeBool(6, dVDOrNDBench_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, cPU_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, netIn_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, netOut_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, memory_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(5, trainingOrTesting_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(6, dVDOrNDBench_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Record)) {
          return super.equals(obj);
        }
        Record other = (Record) obj;

        if (hasCPU() != other.hasCPU()) return false;
        if (hasCPU()) {
          if (Double.doubleToLongBits(getCPU())
              != Double.doubleToLongBits(
                  other.getCPU())) return false;
        }
        if (hasNetIn() != other.hasNetIn()) return false;
        if (hasNetIn()) {
          if (Double.doubleToLongBits(getNetIn())
              != Double.doubleToLongBits(
                  other.getNetIn())) return false;
        }
        if (hasNetOut() != other.hasNetOut()) return false;
        if (hasNetOut()) {
          if (Double.doubleToLongBits(getNetOut())
              != Double.doubleToLongBits(
                  other.getNetOut())) return false;
        }
        if (hasMemory() != other.hasMemory()) return false;
        if (hasMemory()) {
          if (Double.doubleToLongBits(getMemory())
              != Double.doubleToLongBits(
                  other.getMemory())) return false;
        }
        if (hasTrainingOrTesting() != other.hasTrainingOrTesting()) return false;
        if (hasTrainingOrTesting()) {
          if (getTrainingOrTesting()
              != other.getTrainingOrTesting()) return false;
        }
        if (hasDVDOrNDBench() != other.hasDVDOrNDBench()) return false;
        if (hasDVDOrNDBench()) {
          if (getDVDOrNDBench()
              != other.getDVDOrNDBench()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCPU()) {
          hash = (37 * hash) + CPU_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getCPU()));
        }
        if (hasNetIn()) {
          hash = (37 * hash) + NET_IN_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getNetIn()));
        }
        if (hasNetOut()) {
          hash = (37 * hash) + NET_OUT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getNetOut()));
        }
        if (hasMemory()) {
          hash = (37 * hash) + MEMORY_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getMemory()));
        }
        if (hasTrainingOrTesting()) {
          hash = (37 * hash) + TRAINING_OR_TESTING_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getTrainingOrTesting());
        }
        if (hasDVDOrNDBench()) {
          hash = (37 * hash) + DVD_OR_NDBENCH_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getDVDOrNDBench());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Record parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Record parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Record parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Record parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Record parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Record parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Record parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Record parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Record parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Record parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Record parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Record parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Record prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ResponseProto.Record}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ResponseProto.Record)
          RecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Response.internal_static_ResponseProto_Record_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Response.internal_static_ResponseProto_Record_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Record.class, Builder.class);
        }

        // Construct using com.Coen424.Assignment1.Response.ResponseProto.Record.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          cPU_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          netIn_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          netOut_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          memory_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          trainingOrTesting_ = false;
          bitField0_ = (bitField0_ & ~0x00000010);
          dVDOrNDBench_ = false;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Response.internal_static_ResponseProto_Record_descriptor;
        }

        @Override
        public Record getDefaultInstanceForType() {
          return Record.getDefaultInstance();
        }

        @Override
        public Record build() {
          Record result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Record buildPartial() {
          Record result = new Record(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.cPU_ = cPU_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.netIn_ = netIn_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.netOut_ = netOut_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.memory_ = memory_;
            to_bitField0_ |= 0x00000008;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.trainingOrTesting_ = trainingOrTesting_;
            to_bitField0_ |= 0x00000010;
          }
          if (((from_bitField0_ & 0x00000020) != 0)) {
            result.dVDOrNDBench_ = dVDOrNDBench_;
            to_bitField0_ |= 0x00000020;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Record) {
            return mergeFrom((Record)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Record other) {
          if (other == Record.getDefaultInstance()) return this;
          if (other.hasCPU()) {
            setCPU(other.getCPU());
          }
          if (other.hasNetIn()) {
            setNetIn(other.getNetIn());
          }
          if (other.hasNetOut()) {
            setNetOut(other.getNetOut());
          }
          if (other.hasMemory()) {
            setMemory(other.getMemory());
          }
          if (other.hasTrainingOrTesting()) {
            setTrainingOrTesting(other.getTrainingOrTesting());
          }
          if (other.hasDVDOrNDBench()) {
            setDVDOrNDBench(other.getDVDOrNDBench());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          if (!hasCPU()) {
            return false;
          }
          if (!hasNetIn()) {
            return false;
          }
          if (!hasNetOut()) {
            return false;
          }
          if (!hasMemory()) {
            return false;
          }
          if (!hasTrainingOrTesting()) {
            return false;
          }
          if (!hasDVDOrNDBench()) {
            return false;
          }
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Record parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Record) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double cPU_ ;
        /**
         * <code>required double CPU = 1;</code>
         * @return Whether the cPU field is set.
         */
        @Override
        public boolean hasCPU() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required double CPU = 1;</code>
         * @return The cPU.
         */
        @Override
        public double getCPU() {
          return cPU_;
        }
        /**
         * <code>required double CPU = 1;</code>
         * @param value The cPU to set.
         * @return This builder for chaining.
         */
        public Builder setCPU(double value) {
          bitField0_ |= 0x00000001;
          cPU_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double CPU = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCPU() {
          bitField0_ = (bitField0_ & ~0x00000001);
          cPU_ = 0D;
          onChanged();
          return this;
        }

        private double netIn_ ;
        /**
         * <code>required double net_in = 2;</code>
         * @return Whether the netIn field is set.
         */
        @Override
        public boolean hasNetIn() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required double net_in = 2;</code>
         * @return The netIn.
         */
        @Override
        public double getNetIn() {
          return netIn_;
        }
        /**
         * <code>required double net_in = 2;</code>
         * @param value The netIn to set.
         * @return This builder for chaining.
         */
        public Builder setNetIn(double value) {
          bitField0_ |= 0x00000002;
          netIn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double net_in = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNetIn() {
          bitField0_ = (bitField0_ & ~0x00000002);
          netIn_ = 0D;
          onChanged();
          return this;
        }

        private double netOut_ ;
        /**
         * <code>required double net_out = 3;</code>
         * @return Whether the netOut field is set.
         */
        @Override
        public boolean hasNetOut() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required double net_out = 3;</code>
         * @return The netOut.
         */
        @Override
        public double getNetOut() {
          return netOut_;
        }
        /**
         * <code>required double net_out = 3;</code>
         * @param value The netOut to set.
         * @return This builder for chaining.
         */
        public Builder setNetOut(double value) {
          bitField0_ |= 0x00000004;
          netOut_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double net_out = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearNetOut() {
          bitField0_ = (bitField0_ & ~0x00000004);
          netOut_ = 0D;
          onChanged();
          return this;
        }

        private double memory_ ;
        /**
         * <code>required double memory = 4;</code>
         * @return Whether the memory field is set.
         */
        @Override
        public boolean hasMemory() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>required double memory = 4;</code>
         * @return The memory.
         */
        @Override
        public double getMemory() {
          return memory_;
        }
        /**
         * <code>required double memory = 4;</code>
         * @param value The memory to set.
         * @return This builder for chaining.
         */
        public Builder setMemory(double value) {
          bitField0_ |= 0x00000008;
          memory_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double memory = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearMemory() {
          bitField0_ = (bitField0_ & ~0x00000008);
          memory_ = 0D;
          onChanged();
          return this;
        }

        private boolean trainingOrTesting_ ;
        /**
         * <code>required bool training_or_testing = 5;</code>
         * @return Whether the trainingOrTesting field is set.
         */
        @Override
        public boolean hasTrainingOrTesting() {
          return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>required bool training_or_testing = 5;</code>
         * @return The trainingOrTesting.
         */
        @Override
        public boolean getTrainingOrTesting() {
          return trainingOrTesting_;
        }
        /**
         * <code>required bool training_or_testing = 5;</code>
         * @param value The trainingOrTesting to set.
         * @return This builder for chaining.
         */
        public Builder setTrainingOrTesting(boolean value) {
          bitField0_ |= 0x00000010;
          trainingOrTesting_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool training_or_testing = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearTrainingOrTesting() {
          bitField0_ = (bitField0_ & ~0x00000010);
          trainingOrTesting_ = false;
          onChanged();
          return this;
        }

        private boolean dVDOrNDBench_ ;
        /**
         * <code>required bool DVD_or_NDBench = 6;</code>
         * @return Whether the dVDOrNDBench field is set.
         */
        @Override
        public boolean hasDVDOrNDBench() {
          return ((bitField0_ & 0x00000020) != 0);
        }
        /**
         * <code>required bool DVD_or_NDBench = 6;</code>
         * @return The dVDOrNDBench.
         */
        @Override
        public boolean getDVDOrNDBench() {
          return dVDOrNDBench_;
        }
        /**
         * <code>required bool DVD_or_NDBench = 6;</code>
         * @param value The dVDOrNDBench to set.
         * @return This builder for chaining.
         */
        public Builder setDVDOrNDBench(boolean value) {
          bitField0_ |= 0x00000020;
          dVDOrNDBench_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool DVD_or_NDBench = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearDVDOrNDBench() {
          bitField0_ = (bitField0_ & ~0x00000020);
          dVDOrNDBench_ = false;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ResponseProto.Record)
      }

      // @@protoc_insertion_point(class_scope:ResponseProto.Record)
      private static final Record DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Record();
      }

      public static Record getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<Record>
          PARSER = new com.google.protobuf.AbstractParser<Record>() {
        @Override
        public Record parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Record(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Record> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Record> getParserForType() {
        return PARSER;
      }

      @Override
      public Record getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RFW_ID_FIELD_NUMBER = 1;
    private volatile Object rFWID_;
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return Whether the rFWID field is set.
     */
    @Override
    public boolean hasRFWID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The rFWID.
     */
    @Override
    public String getRFWID() {
      Object ref = rFWID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rFWID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string RFW_ID = 1;</code>
     * @return The bytes for rFWID.
     */
    @Override
    public com.google.protobuf.ByteString
        getRFWIDBytes() {
      Object ref = rFWID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rFWID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_BATCH_ID_FIELD_NUMBER = 2;
    private int lastBatchID_;
    /**
     * <code>required int32 last_batch_ID = 2;</code>
     * @return Whether the lastBatchID field is set.
     */
    @Override
    public boolean hasLastBatchID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 last_batch_ID = 2;</code>
     * @return The lastBatchID.
     */
    @Override
    public int getLastBatchID() {
      return lastBatchID_;
    }

    public static final int BATCH_FIELD_NUMBER = 3;
    private java.util.List<Record> batch_;
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    @Override
    public java.util.List<Record> getBatchList() {
      return batch_;
    }
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    @Override
    public java.util.List<? extends RecordOrBuilder>
        getBatchOrBuilderList() {
      return batch_;
    }
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    @Override
    public int getBatchCount() {
      return batch_.size();
    }
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    @Override
    public Record getBatch(int index) {
      return batch_.get(index);
    }
    /**
     * <code>repeated .ResponseProto.Record Batch = 3;</code>
     */
    @Override
    public RecordOrBuilder getBatchOrBuilder(
        int index) {
      return batch_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRFWID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastBatchID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBatchCount(); i++) {
        if (!getBatch(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rFWID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, lastBatchID_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        output.writeMessage(3, batch_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rFWID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastBatchID_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, batch_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponseProto)) {
        return super.equals(obj);
      }
      ResponseProto other = (ResponseProto) obj;

      if (hasRFWID() != other.hasRFWID()) return false;
      if (hasRFWID()) {
        if (!getRFWID()
            .equals(other.getRFWID())) return false;
      }
      if (hasLastBatchID() != other.hasLastBatchID()) return false;
      if (hasLastBatchID()) {
        if (getLastBatchID()
            != other.getLastBatchID()) return false;
      }
      if (!getBatchList()
          .equals(other.getBatchList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRFWID()) {
        hash = (37 * hash) + RFW_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRFWID().hashCode();
      }
      if (hasLastBatchID()) {
        hash = (37 * hash) + LAST_BATCH_ID_FIELD_NUMBER;
        hash = (53 * hash) + getLastBatchID();
      }
      if (getBatchCount() > 0) {
        hash = (37 * hash) + BATCH_FIELD_NUMBER;
        hash = (53 * hash) + getBatchList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponseProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseProto)
        ResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_ResponseProto_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_ResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseProto.class, Builder.class);
      }

      // Construct using com.Coen424.Assignment1.Response.ResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBatchFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rFWID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastBatchID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          batchBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_ResponseProto_descriptor;
      }

      @Override
      public ResponseProto getDefaultInstanceForType() {
        return ResponseProto.getDefaultInstance();
      }

      @Override
      public ResponseProto build() {
        ResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResponseProto buildPartial() {
        ResponseProto result = new ResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rFWID_ = rFWID_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastBatchID_ = lastBatchID_;
          to_bitField0_ |= 0x00000002;
        }
        if (batchBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            batch_ = java.util.Collections.unmodifiableList(batch_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.batch_ = batch_;
        } else {
          result.batch_ = batchBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseProto) {
          return mergeFrom((ResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseProto other) {
        if (other == ResponseProto.getDefaultInstance()) return this;
        if (other.hasRFWID()) {
          bitField0_ |= 0x00000001;
          rFWID_ = other.rFWID_;
          onChanged();
        }
        if (other.hasLastBatchID()) {
          setLastBatchID(other.getLastBatchID());
        }
        if (batchBuilder_ == null) {
          if (!other.batch_.isEmpty()) {
            if (batch_.isEmpty()) {
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBatchIsMutable();
              batch_.addAll(other.batch_);
            }
            onChanged();
          }
        } else {
          if (!other.batch_.isEmpty()) {
            if (batchBuilder_.isEmpty()) {
              batchBuilder_.dispose();
              batchBuilder_ = null;
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000004);
              batchBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBatchFieldBuilder() : null;
            } else {
              batchBuilder_.addAllMessages(other.batch_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasRFWID()) {
          return false;
        }
        if (!hasLastBatchID()) {
          return false;
        }
        for (int i = 0; i < getBatchCount(); i++) {
          if (!getBatch(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object rFWID_ = "";
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return Whether the rFWID field is set.
       */
      public boolean hasRFWID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return The rFWID.
       */
      public String getRFWID() {
        Object ref = rFWID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rFWID_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return The bytes for rFWID.
       */
      public com.google.protobuf.ByteString
          getRFWIDBytes() {
        Object ref = rFWID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rFWID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @param value The rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rFWID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rFWID_ = getDefaultInstance().getRFWID();
        onChanged();
        return this;
      }
      /**
       * <code>required string RFW_ID = 1;</code>
       * @param value The bytes for rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rFWID_ = value;
        onChanged();
        return this;
      }

      private int lastBatchID_ ;
      /**
       * <code>required int32 last_batch_ID = 2;</code>
       * @return Whether the lastBatchID field is set.
       */
      @Override
      public boolean hasLastBatchID() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 last_batch_ID = 2;</code>
       * @return The lastBatchID.
       */
      @Override
      public int getLastBatchID() {
        return lastBatchID_;
      }
      /**
       * <code>required int32 last_batch_ID = 2;</code>
       * @param value The lastBatchID to set.
       * @return This builder for chaining.
       */
      public Builder setLastBatchID(int value) {
        bitField0_ |= 0x00000002;
        lastBatchID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 last_batch_ID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastBatchID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastBatchID_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Record> batch_ =
        java.util.Collections.emptyList();
      private void ensureBatchIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          batch_ = new java.util.ArrayList<Record>(batch_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Record, Record.Builder, RecordOrBuilder> batchBuilder_;

      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public java.util.List<Record> getBatchList() {
        if (batchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(batch_);
        } else {
          return batchBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public int getBatchCount() {
        if (batchBuilder_ == null) {
          return batch_.size();
        } else {
          return batchBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Record getBatch(int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);
        } else {
          return batchBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder setBatch(
          int index, Record value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.set(index, value);
          onChanged();
        } else {
          batchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder setBatch(
          int index, Record.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.set(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder addBatch(Record value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(value);
          onChanged();
        } else {
          batchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder addBatch(
          int index, Record value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(index, value);
          onChanged();
        } else {
          batchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder addBatch(
          Record.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder addBatch(
          int index, Record.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder addAllBatch(
          Iterable<? extends Record> values) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, batch_);
          onChanged();
        } else {
          batchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder clearBatch() {
        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          batchBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Builder removeBatch(int index) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.remove(index);
          onChanged();
        } else {
          batchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Record.Builder getBatchBuilder(
          int index) {
        return getBatchFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public RecordOrBuilder getBatchOrBuilder(
          int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);  } else {
          return batchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public java.util.List<? extends RecordOrBuilder>
           getBatchOrBuilderList() {
        if (batchBuilder_ != null) {
          return batchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(batch_);
        }
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Record.Builder addBatchBuilder() {
        return getBatchFieldBuilder().addBuilder(
            Record.getDefaultInstance());
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public Record.Builder addBatchBuilder(
          int index) {
        return getBatchFieldBuilder().addBuilder(
            index, Record.getDefaultInstance());
      }
      /**
       * <code>repeated .ResponseProto.Record Batch = 3;</code>
       */
      public java.util.List<Record.Builder>
           getBatchBuilderList() {
        return getBatchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Record, Record.Builder, RecordOrBuilder>
          getBatchFieldBuilder() {
        if (batchBuilder_ == null) {
          batchBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Record, Record.Builder, RecordOrBuilder>(
                  batch_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          batch_ = null;
        }
        return batchBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }



      // @@protoc_insertion_point(builder_scope:ResponseProto)
    }

    // @@protoc_insertion_point(class_scope:ResponseProto)
    private static final ResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseProto();
    }

    public static ResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProto>() {
      @Override
      public ResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseProto> getParserForType() {
      return PARSER;
    }

    @Override
    public ResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProto_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseProto_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Response.proto\"\331\001\n\rResponseProto\022\016\n\006RF" +
      "W_ID\030\001 \002(\t\022\025\n\rlast_batch_ID\030\002 \002(\005\022$\n\005Bat" +
      "ch\030\003 \003(\0132\025.ResponseProto.Record\032{\n\006Recor" +
      "d\022\013\n\003CPU\030\001 \002(\001\022\016\n\006net_in\030\002 \002(\001\022\017\n\007net_ou" +
      "t\030\003 \002(\001\022\016\n\006memory\030\004 \002(\001\022\033\n\023training_or_t" +
      "esting\030\005 \002(\010\022\026\n\016DVD_or_NDBench\030\006 \002(\010B\031\n\027" +
      "com.Coen424.Assignment1"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseProto_descriptor,
        new String[] { "RFWID", "LastBatchID", "Batch", });
    internal_static_ResponseProto_Record_descriptor =
      internal_static_ResponseProto_descriptor.getNestedTypes().get(0);
    internal_static_ResponseProto_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseProto_Record_descriptor,
        new String[] { "CPU", "NetIn", "NetOut", "Memory", "TrainingOrTesting", "DVDOrNDBench", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
